---
- name: 시스템 패키지 업데이트
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: EPEL 저장소 설치
  dnf:
    name: epel-release
    state: present

- name: 필수 패키지 설치
  dnf:
    name:
      - curl
      - vim
      - htop
      - net-tools
      - rsync
      - git
      - firewalld
    state: present

- name: 방화벽 시작 및 활성화
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: SSH 포트 개방
  firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: HTTP 포트 개방
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: HTTPS 포트 개방
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

