---
- name: restart httpd
  systemd:
    name: httpd
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

